# Generated by Django 5.1.7 on 2025-03-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='mother_occupation',
            field=models.CharField(default='House Wife', max_length=100),
            preserve_default=False,
        ),
    ]
